apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: qq4
spec:
  replicas: 4
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: httpd:latest