apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard
  namespace: qq5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashboard
  template:
    metadata:
      labels:
        app: dashboard
    spec:
      containers:
      - name: dashboard
        image: drupal:10.2.7-php8.2-fpm-bookworm
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: dashboard
  namespace: qq5
spec:
  selector:
    app: dashboard
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
  type: LoadBalancer