apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: qq3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-deployment
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80