apiVersion: apps/v1
kind: Deployment
metadata:
  name: class
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: class
  template:
    metadata:
      labels:
        app: class
    spec:
      containers:
      - name: class
        image: httpd:alpine3.20
        ports:
        - containerPort: 80
        - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: class-svc
  namespace: default
spec:
  selector:
    app: class
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    - protocol: TCP
      port: 443
      targetPort: 443
  type: ClusterIP