apiVersion: v1
kind: Namespace
metadata:
  name: staging
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeport-app
  namespace: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodeport-demo
  template:
    metadata:
      labels:
        app: nodeport-demo
    spec:
      containers:
      - name: httpd
        image: httpd:latest
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
  namespace: staging
spec:
  type: NodePort
  selector:
    app: nodeport-demo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30000  # You can specify a port in the range 30000-32767 or let Kubernetes assign one