apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-express-config
  namespace: qq3
data:
  ME_CONFIG_MONGODB_URL: "mongodb://root:example@mongo:27017/"
  ME_CONFIG_BASICAUTH: "false"

---

apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: qq3
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: <base64-encoded-username>
  MONGO_INITDB_ROOT_PASSWORD: <base64-encoded-password>
  ME_CONFIG_MONGODB_ADMINUSERNAME: <base64-encoded-username>
  ME_CONFIG_MONGODB_ADMINPASSWORD: <base64-encoded-password>

---


apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
  namespace: qq3
spec:
  serviceName: "database"
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: mongo
        image: mongo:latest
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_INITDB_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_INITDB_ROOT_PASSWORD
      - name: mongo-express
        image: mongo-express:latest
        env:
        - name: ME_CONFIG_MONGODB_URL
          valueFrom:
            configMapKeyRef:
              name: mongo-express-config
              key: ME_CONFIG_MONGODB_URL
        - name: ME_CONFIG_BASICAUTH
          valueFrom:
            configMapKeyRef:
              name: mongo-express-config
              key: ME_CONFIG_BASICAUTH
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: ME_CONFIG_MONGODB_ADMINUSERNAME
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: ME_CONFIG_MONGODB_ADMINPASSWORD